"""Online rollout collection: Qwen policy interacting with VAGEN environments.

The rollout collector runs the Qwen policy in the VAGEN navigation environment,
collecting trajectories that include per-frame images, taken actions, and sparse rewards.
Each trajectory is later encoded into WM latent states by the trainer.
"""

from __future__ import annotations

import gzip
import json
import math
import time

import torch
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Protocol


def validate_rl_policy_protocol(model_config: Any) -> int:
    """Validate the implemented inject runtime and return its query count."""

    latent_count = int(getattr(model_config, "nimloth_latent_token_count", 1))
    query_mode = getattr(model_config, "nimloth_latent_query_mode", None)
    if latent_count < 1 or query_mode != "inject":
        raise ValueError(
            "RL action/encoding runtime requires an inject checkpoint with at least "
            f"one latent query; got latent_token_count={latent_count}, "
            f"latent_query_mode={query_mode!r}"
        )
    return latent_count


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------


@dataclass
class RolloutTrajectory:
    """One exact policy/environment transcript.

    Images and observation texts have length ``num_steps + 1``.  Every other
    per-step list has length ``num_steps``.  Keeping the generated assistant
    response and VAGEN reward at their original turn prevents PPO/WM replay
    from silently constructing a different prompt or reward sequence.
    """

    record_id: str
    image_paths: list[str] = field(default_factory=list)
    observation_texts: list[str] = field(default_factory=list)
    task_instruction: str = ""
    system_prompt: str = ""
    assistant_responses: list[str] = field(default_factory=list)
    action_indices: list[int] = field(default_factory=list)
    action_names: list[str] = field(default_factory=list)
    action_log_probs: list[list[float]] = field(default_factory=list)
    step_rewards: list[float] = field(default_factory=list)
    final_reward: float = 0.0
    success: bool = False
    reward: float = 0.0
    split: str = "train"
    latent_token_count: int = 1

    @property
    def num_steps(self) -> int:
        return len(self.action_indices)

    @property
    def messages(self) -> list[dict[str, str]]:
        """Return only turns actually consumed/generated by the policy.

        The final observation is retained for environment/WM alignment, but no
        assistant action was requested from it and it is therefore not appended
        as a trailing user message.
        """

        messages = [{"role": "system", "content": self.system_prompt}]
        for observation, response in zip(
            self.observation_texts[:-1], self.assistant_responses
        ):
            messages.append({"role": "user", "content": observation})
            messages.append({"role": "assistant", "content": response})
        return messages

    def to_record(self) -> dict[str, Any]:
        """Serialize the lossless trajectory protocol."""
        return {
            "id": self.record_id,
            "split": self.split,
            "success": self.success,
            "reward": self.reward,
            "final_reward": self.final_reward,
            "step_rewards": self.step_rewards,
            "system_prompt": self.system_prompt,
            "task_instruction": self.task_instruction,
            "observation_texts": self.observation_texts,
            "assistant_responses": self.assistant_responses,
            "messages": self.messages,
            "image_paths": self.image_paths,
            "action_indices": self.action_indices,
            "action_names": self.action_names,
            "action_log_probs": self.action_log_probs,
            "latent_token_count": self.latent_token_count,
        }

    @classmethod
    def from_record(cls, record: dict[str, Any]) -> "RolloutTrajectory":
        required = (
            "system_prompt",
            "task_instruction",
            "observation_texts",
            "assistant_responses",
            "step_rewards",
        )
        missing = [key for key in required if key not in record]
        if missing:
            raise ValueError(
                "legacy/taskless rollout record is not valid for RL replay; "
                f"missing={missing}"
            )
        return cls(
            record_id=str(record.get("id", "")),
            image_paths=list(record.get("image_paths", [])),
            observation_texts=[str(value) for value in record["observation_texts"]],
            task_instruction=str(record["task_instruction"]),
            system_prompt=str(record["system_prompt"]),
            assistant_responses=[str(value) for value in record["assistant_responses"]],
            action_indices=[int(value) for value in record.get("action_indices", [])],
            action_names=[str(value) for value in record.get("action_names", [])],
            action_log_probs=list(record.get("action_log_probs", [])),
            step_rewards=[float(value) for value in record["step_rewards"]],
            final_reward=float(record.get("final_reward", 0.0)),
            success=bool(record.get("success", False)),
            reward=float(record.get("reward", 0.0)),
            split=str(record.get("split", "train")),
            latent_token_count=int(record.get("latent_token_count", 1)),
        )


# ---------------------------------------------------------------------------
# Collector interface
# ---------------------------------------------------------------------------


class RolloutCollector(Protocol):
    """Interface for collecting trajectories from an environment."""

    def collect(
        self,
        *,
        num_episodes: int,
        max_steps_per_episode: int = 20,
        output_dir: Path | None = None,
    ) -> list[RolloutTrajectory]:
        """Run ``num_episodes`` episodes and return collected trajectories."""
        ...


# ---------------------------------------------------------------------------
# VAGEN-backed collector (delegates to VAGEN's trainer.val_only rollout)
# ---------------------------------------------------------------------------


class VAGENRolloutCollector:
    """Collect trajectories by running VAGEN in validation-only mode.

    Legacy placeholder — use ``EnvRolloutCollector`` for direct env interaction.
    """

    def __init__(
        self,
        vagen_config_path: Path,
        vagen_checkpoint_dir: Path,
        output_root: Path,
    ) -> None:
        self._vagen_config_path = vagen_config_path
        self._vagen_checkpoint_dir = vagen_checkpoint_dir
        self._output_root = output_root

    def collect(self, *, num_episodes, max_steps_per_episode=20, output_dir=None):
        raise NotImplementedError(
            "VAGENRolloutCollector is not implemented. Use EnvRolloutCollector with --env-url."
        )


# ---------------------------------------------------------------------------
# Env-backed collector (direct env server interaction using trainer's Qwen)
# ---------------------------------------------------------------------------

from nimloth.training.rl.vagen_protocol import (  # noqa: E402
    ACTION_NAMES as _ACTION_NAMES,
    ACTION_NAME_TO_IDX,
)

ACTION_NAMES: list[str] = list(_ACTION_NAMES)
ACTION_NAME_MAP: dict[str, int] = dict(ACTION_NAME_TO_IDX)


class EnvRolloutCollector:
    """Collect trajectories by running Qwen policy against the VAGEN env server.

    Reuses the trainer's Qwen model (no subprocess/model-reloading).
    Each ``collect()`` call creates envs on the server, runs Qwen-based
    greedy action selection, and returns ``RolloutTrajectory`` objects.
    """

    def __init__(
        self,
        qwen_model,
        processor,
        env_url: str,
        device,
        seed_offset: int = 0,
        temperature: float = 1.0,
        top_p: float = 1.0,
        eval_sets: tuple[str, ...] = ("base", "common_sense"),
        split: str = "eval",
        history_window: int = 112,
        env_timeout: int = 180,
        latent_token_count: int = 1,
        max_think_tokens: int = 512,
    ) -> None:
        if not eval_sets:
            raise ValueError("EnvRolloutCollector requires at least one eval_set")
        if split == "train" and any(not name.endswith("_train") for name in eval_sets):
            raise ValueError(
                "training rollout requires *_train datasets; "
                f"got eval_sets={eval_sets}"
            )
        if split == "validation" and any(name.endswith("_train") for name in eval_sets):
            raise ValueError(
                "heldout validation forbids *_train datasets; "
                f"got eval_sets={eval_sets}"
            )
        self._model = qwen_model
        self._processor = processor
        self._env_url = env_url.rstrip("/")
        self._device = device
        self._base_seed_offset = int(seed_offset)
        self._ep_counter = int(seed_offset)
        self._client = None  # lazy init
        self._temperature = temperature
        self._top_p = top_p
        self._eval_sets = eval_sets
        self._split = split
        if latent_token_count < 1:
            raise ValueError(
                f"latent_token_count must be >= 1, got {latent_token_count}"
            )
        self._latent_token_count = int(latent_token_count)
        if history_window < 0:
            raise ValueError(f"history_window must be >= 0, got {history_window}")
        self._history_window = int(history_window)
        if env_timeout <= 0:
            raise ValueError(f"env_timeout must be > 0, got {env_timeout}")
        self._env_timeout = int(env_timeout)
        if max_think_tokens <= 0:
            raise ValueError(f"max_think_tokens must be > 0, got {max_think_tokens}")
        self._max_think_tokens = int(max_think_tokens)

    @property
    def client(self):
        if self._client is None:
            from vagen.server.client import BatchEnvClient
            self._client = BatchEnvClient(
                base_url=self._env_url, timeout=self._env_timeout
            )
        return self._client

    def _environment_config(self, eval_set: str) -> dict[str, Any]:
        """Return the pinned source_eval_mode SFT-collection environment."""

        return {
            "env_name": "navigation",
            "env_config": {
                "render_mode": "vision",
                "prompt_format": "source_eval_mode",
                "use_state_reward": False,
                "eval_set": eval_set,
                "max_actions_per_step": 1,
                "action_sep": "|",
                "example_count": 0,
                "format_reward": 0.0,
                "per_turn_format_reward": 0.01,
                "success_reward": 1.0,
                "success_threshold": 1.0,
                "step_length": 0.3,
                "grounding_reward_weight": 0.5,
                "worldmodeling_reward_weight": 0.5,
                "gpu_device": 0,
            },
        }

    def _sampling_seed(self, episode_seed: int, step: int) -> int:
        # Sampling is a pure function of env seed + step, so checkpoint resume
        # does not depend on a process-local RNG state.
        return int((self._base_seed_offset + 1) * 1_000_003 + episode_seed * 997 + step)

    def reset_seed_cursor(self) -> None:
        """Reset to the fixed base seed (used for repeatable heldout evaluation)."""

        self._ep_counter = self._base_seed_offset

    def set_resume_iteration(
        self,
        *,
        start_iteration: int,
        envs_per_iteration: int,
        validation_enabled: bool,
        validation_interval: int,
        validation_envs: int,
    ) -> None:
        """Restore the deterministic environment-seed cursor for resume."""

        completed = max(0, int(start_iteration) - 1)
        consumed = completed * int(envs_per_iteration)
        if validation_enabled and validation_interval > 0:
            consumed += (completed // int(validation_interval)) * int(validation_envs)
        self._ep_counter = self._base_seed_offset + consumed

    def collect(
        self,
        *,
        num_episodes: int,
        max_steps_per_episode: int = 20,
        output_dir: Path | None = None,
    ) -> list[RolloutTrajectory]:

        out_dir = output_dir or Path(".")
        out_dir.mkdir(parents=True, exist_ok=True)
        img_dir = out_dir / "images"
        img_dir.mkdir(parents=True, exist_ok=True)
        print(json.dumps({"rl_collect": "start", "num_episodes": num_episodes,
                          "output": str(out_dir)}), flush=True)

        # --- lazy-init client -------------------------------------------------
        if self._client is None:
            print(json.dumps({"rl_collect": "init_client", "url": self._env_url}), flush=True)
            try:
                from vagen.server.client import BatchEnvClient
                self._client = BatchEnvClient(
                    base_url=self._env_url, timeout=self._env_timeout
                )
                print(json.dumps({"rl_collect": "client_created"}), flush=True)
            except Exception:
                import traceback
                traceback.print_exc()
                print(json.dumps({"rl_collect": "client_init_failed"}), flush=True)
                raise

        trajectories: list[RolloutTrajectory] = []

        for ep_i in range(num_episodes):
            seed = self._ep_counter
            ep_id = f"rl_{seed:06d}"
            self._ep_counter += 1
            t0 = time.time()
            eval_set = self._eval_sets[ep_i % len(self._eval_sets)]

            print(json.dumps({"rl_ep": ep_i, "id": ep_id, "eval_set": eval_set}), flush=True)

            env_config = self._environment_config(eval_set)

            # --- create env on server ---
            print(json.dumps({"rl_ep": ep_i, "step": "create_env"}), flush=True)
            try:
                self._client.create_environments_batch({ep_id: env_config})
                print(json.dumps({"rl_ep": ep_i, "step": "create_env_done"}), flush=True)
            except Exception:
                import traceback
                traceback.print_exc()
                print(json.dumps({"rl_ep": ep_i, "step": "create_env_failed",
                                  "error": str(traceback.format_exc())}), flush=True)
                continue

            # --- get system prompt ---
            print(json.dumps({"rl_ep": ep_i, "step": "get_prompt"}), flush=True)
            try:
                from nimloth.training.rl.vagen_protocol import source_eval_text_to_nimloth

                prompts = self._client.get_system_prompts_batch([ep_id])
                raw_system_prompt = str(prompts.get(ep_id, "")).strip()
                if not raw_system_prompt:
                    raise RuntimeError(f"environment returned no system prompt for {ep_id}")
                system_prompt = source_eval_text_to_nimloth(
                    raw_system_prompt,
                    latent_token_count=self._latent_token_count,
                )
                print(json.dumps({"rl_ep": ep_i, "step": "get_prompt_done"}), flush=True)
            except Exception:
                import traceback
                traceback.print_exc()
                try:
                    self._client.close_batch([ep_id])
                except Exception:
                    pass
                continue

            # --- reset ---
            print(json.dumps({"rl_ep": ep_i, "step": "reset", "seed": seed}), flush=True)
            try:
                results = self._client.reset_batch({ep_id: seed})
                obs, info = results[ep_id]
                print(json.dumps({"rl_ep": ep_i, "step": "reset_done"}), flush=True)
            except Exception:
                import traceback
                traceback.print_exc()
                print(json.dumps({"rl_ep": ep_i, "step": "reset_failed",
                                  "error": str(traceback.format_exc())}), flush=True)
                try:
                    self._client.close_batch([ep_id])
                except Exception:
                    pass
                continue

            action_names: list[str] = []
            action_indices: list[int] = []
            action_log_probs: list[list[float]] = []
            assistant_responses: list[str] = []
            image_paths: list[str] = []
            observation_texts: list[str] = []
            task_instruction = ""
            done = False
            step_rewards: list[float] = []
            success = False
            episode_valid = True

            for step in range(max_steps_per_episode):
                print(json.dumps({"rl_ep": ep_i, "step": f"action_{step}", "history_len": len(action_names)}), flush=True)

                # VAGEN owns both the image and the policy-visible text.
                try:
                    from nimloth.training.rl.vagen_protocol import (
                        extract_human_instruction,
                        nimloth_assistant_response,
                        observation_text_and_image,
                        task_succeeded,
                        vagen_env_response,
                    )

                    observation_text, img = observation_text_and_image(
                        obs, latent_token_count=self._latent_token_count
                    )
                    if not observation_texts:
                        task_instruction = extract_human_instruction(observation_text)
                except Exception:
                    import traceback
                    traceback.print_exc()
                    episode_valid = False
                    break

                img_path = img_dir / f"{ep_id}_step{step:02d}.png"
                img.save(str(img_path))
                image_paths.append(str(img_path))
                observation_texts.append(observation_text)

                try:
                    generator = torch.Generator(device="cpu")
                    generator.manual_seed(self._sampling_seed(seed, step))
                    thought, action_name, action_idx, log_probs_list = _select_action_nimloth(
                        self._model,
                        self._processor,
                        image_paths,
                        system_prompt,
                        observation_texts,
                        assistant_responses,
                        temperature=self._temperature,
                        top_p=self._top_p,
                        history_window=self._history_window,
                        latent_token_count=self._latent_token_count,
                        max_think_tokens=self._max_think_tokens,
                        generator=generator,
                    )
                    assistant_response = nimloth_assistant_response(
                        thought,
                        action_idx,
                        latent_token_count=self._latent_token_count,
                    )
                    env_response = vagen_env_response(thought, action_idx)
                    print(json.dumps({"rl_ep": ep_i, "action_selected": action_name,
                                      "action_idx": action_idx}), flush=True)
                except Exception:
                    import traceback
                    traceback.print_exc()
                    episode_valid = False
                    break

                try:
                    step_results = self._client.step_batch({ep_id: env_response})
                    obs, r, done, info = step_results[ep_id]
                    if not isinstance(info, dict) or str(info.get("instruction", "")) != task_instruction:
                        raise RuntimeError(
                            "environment task changed or disagrees with initial observation: "
                            f"initial={task_instruction!r}, step_info="
                            f"{info.get('instruction') if isinstance(info, dict) else None!r}"
                        )
                    step_rewards.append(float(r))
                    success = success or task_succeeded(info)
                    action_ok = info.get("last_action_success", True) if isinstance(info, dict) else True
                    print(json.dumps({"rl_ep": ep_i, "env_step_done": True, "done": done,
                                      "step_reward": r, "action_ok": action_ok}), flush=True)
                except Exception:
                    import traceback
                    traceback.print_exc()
                    episode_valid = False
                    break

                action_names.append(action_name)
                action_indices.append(action_idx)
                action_log_probs.append(log_probs_list)
                assistant_responses.append(assistant_response)

                if done:
                    break

            final_reward = 0.0
            try:
                from nimloth.training.rl.vagen_protocol import observation_text_and_image

                final_text, final_img = observation_text_and_image(
                    obs, latent_token_count=self._latent_token_count
                )
                img_path = img_dir / f"{ep_id}_step{len(action_names):02d}.png"
                final_img.save(str(img_path))
                image_paths.append(str(img_path))
                observation_texts.append(final_text)
                rewards = self._client.compute_reward_batch([ep_id])
                if ep_id not in rewards:
                    raise RuntimeError(f"environment returned no final reward for {ep_id}")
                final_reward = float(rewards[ep_id])
            except Exception:
                import traceback
                traceback.print_exc()
                episode_valid = False

            reward = sum(step_rewards) + final_reward

            try:
                self._client.close_batch([ep_id])
            except Exception:
                pass

            if not episode_valid or not action_names or len(image_paths) != len(action_names) + 1:
                print(json.dumps({
                    "rl_ep": ep_i,
                    "warning": "discarding incomplete trajectory",
                    "num_actions": len(action_names),
                    "num_images": len(image_paths),
                }), flush=True)
                continue

            trajectory = RolloutTrajectory(
                record_id=ep_id,
                image_paths=image_paths,
                observation_texts=observation_texts,
                task_instruction=task_instruction,
                system_prompt=system_prompt,
                assistant_responses=assistant_responses,
                action_indices=action_indices,
                action_names=list(action_names),
                action_log_probs=action_log_probs,
                step_rewards=step_rewards,
                final_reward=final_reward,
                success=success,
                reward=reward,
                split=self._split,
                latent_token_count=self._latent_token_count,
            )
            validate_rollout_trajectory(trajectory)
            trajectories.append(trajectory)

            elapsed = time.time() - t0
            print(json.dumps({
                "rl_ep": ep_i, "done": True,
                "steps": len(action_names),
                "success": success,
                "reward": round(reward, 2),
                "elapsed_s": round(elapsed, 1),
            }), flush=True)

        jsonl_path = save_trajectories(trajectories, out_dir)
        print(json.dumps({
            "rl_collect": "done",
            "trajectories": len(trajectories),
            "jsonl_path": str(jsonl_path),
        }), flush=True)
        return trajectories


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def build_nimloth_policy_messages(
    image_history: list[Any],
    system_prompt: str,
    observation_texts: list[str],
    assistant_responses: list[str],
    *,
    history_window: int,
) -> tuple[list[dict[str, str]], list[Any]]:
    """Build the exact SFT-format history from environment/policy records."""

    from nimloth.training.rl.vagen_protocol import trajectory_messages

    if len(image_history) != len(observation_texts):
        raise ValueError(
            "policy history requires one image per observation text: "
            f"images={len(image_history)}, observations={len(observation_texts)}"
        )
    messages = trajectory_messages(
        system_prompt,
        observation_texts,
        assistant_responses,
        history_window=history_window,
    )
    start = max(0, len(assistant_responses) - history_window)
    return messages, list(image_history[start:])


def materialize_policy_images(images: list[Any]) -> list[Any]:
    """Load path-backed history as RGB PIL images for Qwen's fast processor."""

    from PIL import Image

    materialized: list[Any] = []
    for image in images:
        if isinstance(image, (str, Path)):
            with Image.open(image) as source:
                materialized.append(source.convert("RGB").copy())
        elif isinstance(image, Image.Image):
            materialized.append(image.convert("RGB"))
        else:
            raise ValueError(f"unsupported policy image type: {type(image)}")
    return materialized


def multimodal_policy_messages(
    messages: list[dict[str, Any]], images: list[Any]
) -> tuple[list[dict[str, Any]], list[Any]]:
    """Attach real images to transcript placeholders exactly as SFT batching does."""

    from nimloth.wm.collate import messages_with_image_paths

    materialized = materialize_policy_images(images)
    string_placeholders = 0
    multimodal_parts = 0
    for message in messages:
        content = message.get("content")
        if isinstance(content, str):
            string_placeholders += content.count("<image>")
        elif isinstance(content, list):
            multimodal_parts += sum(
                1 for part in content
                if isinstance(part, dict) and part.get("type") == "image"
            )
    if string_placeholders and multimodal_parts:
        raise ValueError(
            "policy messages cannot mix string <image> placeholders and image parts"
        )
    placeholder_count = string_placeholders + multimodal_parts
    if placeholder_count != len(materialized):
        raise ValueError(
            "policy image placeholder count must equal image count: "
            f"placeholders={placeholder_count}, images={len(materialized)}"
        )
    if string_placeholders:
        return messages_with_image_paths(messages, materialized), materialized
    if not multimodal_parts:
        return [dict(message) for message in messages], materialized

    image_iter = iter(materialized)
    attached: list[dict[str, Any]] = []
    for message in messages:
        copied = dict(message)
        content = copied.get("content")
        if isinstance(content, list):
            copied_parts: list[Any] = []
            for part in content:
                if isinstance(part, dict) and part.get("type") == "image":
                    copied_part = dict(part)
                    copied_part["image"] = next(image_iter)
                    copied_parts.append(copied_part)
                else:
                    copied_parts.append(dict(part) if isinstance(part, dict) else part)
            copied["content"] = copied_parts
        attached.append(copied)
    return attached, materialized


def policy_inputs_from_messages(
    model,
    processor,
    messages: list[dict[str, Any]],
    images: list[Any],
) -> tuple[dict[str, torch.Tensor], str]:
    """Apply the training chat template to an exact multimodal history."""

    messages, materialized_images = multimodal_policy_messages(messages, images)
    rendered = processor.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True
    )
    inputs = processor(
        text=[rendered],
        images=materialized_images,
        return_tensors="pt",
        padding=True,
    )
    try:
        device = next(model.parameters()).device
    except StopIteration as exc:
        raise RuntimeError("policy model has no parameters") from exc
    return {
        key: value.to(device) if isinstance(value, torch.Tensor) else value
        for key, value in inputs.items()
    }, rendered


def _policy_inputs(
    model,
    processor,
    image_history: list[Any],
    system_prompt: str,
    observation_texts: list[str],
    assistant_responses: list[str],
    *,
    history_window: int,
) -> tuple[dict[str, torch.Tensor], str]:
    messages, images = build_nimloth_policy_messages(
        image_history,
        system_prompt,
        observation_texts,
        assistant_responses,
        history_window=history_window,
    )
    return policy_inputs_from_messages(model, processor, messages, images)


def _append_input_token(inputs: dict[str, Any], token_id: int) -> dict[str, Any]:
    result = dict(inputs)
    ids = result["input_ids"]
    token = torch.tensor([[int(token_id)]], dtype=ids.dtype, device=ids.device)
    result["input_ids"] = torch.cat((ids, token), dim=1)
    if "attention_mask" in result:
        mask = result["attention_mask"]
        one = torch.ones((mask.shape[0], 1), dtype=mask.dtype, device=mask.device)
        result["attention_mask"] = torch.cat((mask, one), dim=1)
    result.pop("position_ids", None)
    return result


def _action_logits_from_inputs(
    model,
    processor,
    inputs: dict[str, Any],
    *,
    latent_token_count: int,
) -> torch.Tensor:
    from nimloth.latent.extraction import (
        LatentActionTokens,
        latent_state_tokens,
        special_token_ids,
    )

    tokens = LatentActionTokens()
    token_ids = special_token_ids(
        processor.tokenizer, tokens, latent_token_count=latent_token_count
    )
    for query_name in latent_state_tokens(latent_token_count, tokens):
        inputs = _append_input_token(inputs, token_ids[query_name])
    inputs = _append_input_token(inputs, token_ids[tokens.action_start])
    with torch.no_grad():
        outputs = model(**inputs, output_hidden_states=False, return_dict=True)
    action_ids = torch.tensor(
        [token_ids[token] for token in tokens.action_tokens],
        device=outputs.logits.device,
    )
    action_logits = outputs.logits[0, -1, action_ids].float()
    if action_logits.shape != (len(ACTION_NAMES),):
        raise RuntimeError(f"unexpected action logits shape: {tuple(action_logits.shape)}")
    if not torch.isfinite(action_logits).all():
        raise RuntimeError("action logits contain non-finite values")
    return action_logits


def compute_nimloth_action_distribution(
    model,
    processor,
    image_history: list[Any],
    system_prompt: str,
    observation_texts: list[str],
    assistant_responses: list[str],
    current_thought: str,
    *,
    history_window: int,
    latent_token_count: int = 1,
) -> tuple[torch.Tensor, torch.Tensor]:
    """Recompute one stored policy turn without inventing any prompt text."""

    import re

    if re.fullmatch(r"<think>.*?</think>", current_thought.strip(), re.DOTALL) is None:
        raise ValueError("current_thought must be one complete <think> block")
    inputs, _ = _policy_inputs(
        model,
        processor,
        image_history,
        system_prompt,
        observation_texts,
        assistant_responses,
        history_window=history_window,
    )
    thought_ids = processor.tokenizer.encode(
        current_thought.strip(), add_special_tokens=False
    )
    for token_id in thought_ids:
        inputs = _append_input_token(inputs, token_id)
    action_logits = _action_logits_from_inputs(
        model,
        processor,
        inputs,
        latent_token_count=latent_token_count,
    )
    return action_logits, torch.log_softmax(action_logits, dim=-1)


def _generate_nimloth_thought_from_inputs(
    model,
    processor,
    inputs: dict[str, Any],
    *,
    latent_token_count: int,
    max_think_tokens: int,
    token_selector,
) -> tuple[str, torch.Tensor]:
    import re

    if max_think_tokens <= 0:
        raise ValueError(f"max_think_tokens must be > 0, got {max_think_tokens}")
    closing_ids = processor.tokenizer.encode("</think>", add_special_tokens=False)
    if not closing_ids:
        raise RuntimeError("tokenizer produced no ids for </think>")
    generated: list[int] = []
    for token_index in range(max_think_tokens):
        with torch.no_grad():
            outputs = model(**inputs, output_hidden_states=False, return_dict=True)
        next_logits = outputs.logits[0, -1].float()
        if not torch.isfinite(next_logits).all():
            raise RuntimeError("thought logits contain non-finite values")
        token_id = int(token_selector(next_logits, token_index))
        generated.append(token_id)
        inputs = _append_input_token(inputs, token_id)
        if len(generated) >= len(closing_ids) and generated[-len(closing_ids):] == closing_ids:
            break
    else:
        raise RuntimeError(
            f"policy did not emit </think> within {max_think_tokens} tokens"
        )
    thought = processor.tokenizer.decode(generated, skip_special_tokens=False).strip()
    if re.fullmatch(r"<think>.*?</think>", thought, re.DOTALL) is None:
        raise RuntimeError(f"policy emitted malformed thought block: {thought!r}")
    action_logits = _action_logits_from_inputs(
        model,
        processor,
        inputs,
        latent_token_count=latent_token_count,
    )
    return thought, action_logits


def generate_nimloth_thought_and_action_logits_from_messages(
    model,
    processor,
    messages: list[dict[str, Any]],
    images: list[Any],
    *,
    latent_token_count: int,
    max_think_tokens: int,
    token_selector,
) -> tuple[str, torch.Tensor]:
    """Run the inject protocol from an exact SFT-format message prefix."""

    inputs, _ = policy_inputs_from_messages(model, processor, messages, images)
    return _generate_nimloth_thought_from_inputs(
        model,
        processor,
        inputs,
        latent_token_count=latent_token_count,
        max_think_tokens=max_think_tokens,
        token_selector=token_selector,
    )


def generate_nimloth_thought_and_action_logits(
    model,
    processor,
    image_history: list[Any],
    system_prompt: str,
    observation_texts: list[str],
    assistant_responses: list[str],
    *,
    history_window: int,
    latent_token_count: int,
    max_think_tokens: int,
    token_selector,
) -> tuple[str, torch.Tensor]:
    """Generate the SFT-trained thought, then framework-inject latent queries."""

    inputs, _ = _policy_inputs(
        model,
        processor,
        image_history,
        system_prompt,
        observation_texts,
        assistant_responses,
        history_window=history_window,
    )
    return _generate_nimloth_thought_from_inputs(
        model,
        processor,
        inputs,
        latent_token_count=latent_token_count,
        max_think_tokens=max_think_tokens,
        token_selector=token_selector,
    )


def sample_action_from_logits(
    action_logits: torch.Tensor,
    *,
    temperature: float,
    top_p: float,
    generator: torch.Generator | None = None,
) -> tuple[int, list[float]]:
    """Sample one action and return temperature-scaled full log-probs.

    Top-p only restricts sampling.  PPO log-probs use the full temperature-scaled
    distribution, matching VAGEN/VERL's recompute-log-prob convention.
    """

    if action_logits.shape != (len(ACTION_NAMES),):
        raise ValueError(f"expected 8 action logits, got {tuple(action_logits.shape)}")
    if temperature < 0:
        raise ValueError(f"temperature must be >= 0, got {temperature}")
    if not 0 < top_p <= 1:
        raise ValueError(f"top_p must be in (0, 1], got {top_p}")

    logits = action_logits.detach().float().cpu()
    if temperature == 0:
        chosen_idx = int(logits.argmax().item())
        log_probs = torch.log_softmax(logits, dim=-1)
        return chosen_idx, [float(value) for value in log_probs.tolist()]

    scaled = logits / temperature
    log_probs = torch.log_softmax(scaled, dim=-1)
    sampling_logits = scaled.clone()
    if top_p < 1.0:
        sorted_logits, sorted_indices = torch.sort(sampling_logits, descending=True)
        sorted_probs = torch.softmax(sorted_logits, dim=-1)
        cumulative_before = torch.cumsum(sorted_probs, dim=-1) - sorted_probs
        keep = cumulative_before < top_p
        keep[0] = True
        keep_mask = torch.zeros_like(sampling_logits, dtype=torch.bool)
        keep_mask[sorted_indices[keep]] = True
        sampling_logits[~keep_mask] = float("-inf")
    probabilities = torch.softmax(sampling_logits, dim=-1)
    chosen_idx = int(torch.multinomial(probabilities, 1, generator=generator).item())
    return chosen_idx, [float(value) for value in log_probs.tolist()]


def sample_token_from_logits(
    logits: torch.Tensor,
    *,
    temperature: float,
    top_p: float,
    generator: torch.Generator | None = None,
) -> int:
    """Sample one vocabulary token with the rollout temperature/top-p rules."""

    if logits.ndim != 1:
        raise ValueError(f"expected one-dimensional token logits, got {tuple(logits.shape)}")
    if temperature < 0:
        raise ValueError(f"temperature must be >= 0, got {temperature}")
    if not 0 < top_p <= 1:
        raise ValueError(f"top_p must be in (0, 1], got {top_p}")
    values = logits.detach().float().cpu()
    if temperature == 0:
        return int(values.argmax().item())
    values = values / temperature
    if top_p < 1.0:
        sorted_logits, sorted_indices = torch.sort(values, descending=True)
        sorted_probs = torch.softmax(sorted_logits, dim=-1)
        cumulative_before = torch.cumsum(sorted_probs, dim=-1) - sorted_probs
        keep = cumulative_before < top_p
        keep[0] = True
        mask = torch.zeros_like(values, dtype=torch.bool)
        mask[sorted_indices[keep]] = True
        values[~mask] = float("-inf")
    return int(torch.multinomial(
        torch.softmax(values, dim=-1), 1, generator=generator
    ).item())


def _select_action_nimloth(
    model,
    processor,
    image_history: list[Any],
    system_prompt: str,
    observation_texts: list[str],
    assistant_responses: list[str],
    *,
    temperature: float = 1.0,
    top_p: float = 1.0,
    history_window: int = 112,
    latent_token_count: int = 1,
    max_think_tokens: int = 512,
    generator: torch.Generator | None = None,
) -> tuple[str, str, int, list[float]]:
    """Generate the actual assistant thought, inject queries, and sample action."""

    thought, action_logits = generate_nimloth_thought_and_action_logits(
        model,
        processor,
        image_history,
        system_prompt,
        observation_texts,
        assistant_responses,
        history_window=history_window,
        latent_token_count=latent_token_count,
        max_think_tokens=max_think_tokens,
        token_selector=lambda logits, _: sample_token_from_logits(
            logits,
            temperature=temperature,
            top_p=top_p,
            generator=generator,
        ),
    )
    chosen_idx, log_probs = sample_action_from_logits(
        action_logits,
        temperature=temperature,
        top_p=top_p,
        generator=generator,
    )
    return thought, ACTION_NAMES[chosen_idx], chosen_idx, log_probs


def validate_rollout_trajectory(trajectory: RolloutTrajectory) -> None:
    """Reject lossy, taskless, or numerically invalid policy trajectories."""

    from nimloth.training.rl.vagen_protocol import (
        ACTION_NAME_TO_IDX,
        extract_human_instruction,
        nimloth_assistant_response,
    )

    steps = trajectory.num_steps
    if steps <= 0:
        raise ValueError(f"trajectory {trajectory.record_id!r} has no actions")
    lengths = {
        "images": len(trajectory.image_paths),
        "observation_texts": len(trajectory.observation_texts),
    }
    for name, length in lengths.items():
        if length != steps + 1:
            raise ValueError(
                f"trajectory {trajectory.record_id!r}: {name}={length} but actions={steps}"
            )
    per_step = {
        "action_names": len(trajectory.action_names),
        "action_log_probs": len(trajectory.action_log_probs),
        "assistant_responses": len(trajectory.assistant_responses),
        "step_rewards": len(trajectory.step_rewards),
    }
    for name, length in per_step.items():
        if length != steps:
            raise ValueError(
                f"trajectory {trajectory.record_id!r}: {name}={length} but actions={steps}"
            )
    if not trajectory.system_prompt.strip():
        raise ValueError(f"trajectory {trajectory.record_id!r} has no system prompt")
    extracted_instruction = extract_human_instruction(trajectory.observation_texts[0])
    if trajectory.task_instruction != extracted_instruction:
        raise ValueError(
            f"trajectory {trajectory.record_id!r}: task_instruction does not match "
            "the initial environment observation"
        )
    for index, text in enumerate(trajectory.observation_texts):
        if text.count("<image>") != 1:
            raise ValueError(
                f"trajectory {trajectory.record_id!r}: observation {index} must have one <image>"
            )
    for step, (action_idx, action_name, log_probs, response, step_reward) in enumerate(zip(
        trajectory.action_indices,
        trajectory.action_names,
        trajectory.action_log_probs,
        trajectory.assistant_responses,
        trajectory.step_rewards,
    )):
        if not 0 <= int(action_idx) < len(ACTION_NAMES):
            raise ValueError(f"trajectory {trajectory.record_id!r}: invalid action {action_idx}")
        if ACTION_NAME_TO_IDX.get(action_name) != int(action_idx):
            raise ValueError(
                f"trajectory {trajectory.record_id!r}: action name/index mismatch at step {step}"
            )
        if len(log_probs) != len(ACTION_NAMES):
            raise ValueError(
                f"trajectory {trajectory.record_id!r}: step {step} has "
                f"{len(log_probs)} action log-probs"
            )
        if not all(math.isfinite(float(value)) for value in log_probs):
            raise ValueError(
                f"trajectory {trajectory.record_id!r}: step {step} has non-finite log-probs"
            )
        probability_sum = sum(math.exp(float(value)) for value in log_probs)
        if not math.isclose(probability_sum, 1.0, rel_tol=1e-5, abs_tol=1e-5):
            raise ValueError(
                f"trajectory {trajectory.record_id!r}: step {step} action "
                f"log-probs are not normalized (sum={probability_sum})"
            )
        if not math.isfinite(float(step_reward)):
            raise ValueError(
                f"trajectory {trajectory.record_id!r}: step {step} has non-finite reward"
            )
        thought_end = response.find("</think>")
        if thought_end < 0:
            raise ValueError(
                f"trajectory {trajectory.record_id!r}: step {step} has no complete thought"
            )
        thought = response[:thought_end + len("</think>")]
        expected = nimloth_assistant_response(
            thought,
            int(action_idx),
            latent_token_count=trajectory.latent_token_count,
        )
        if response != expected:
            raise ValueError(
                f"trajectory {trajectory.record_id!r}: step {step} assistant response "
                "does not match the inject training format"
            )
    if not math.isfinite(float(trajectory.final_reward)):
        raise ValueError(f"trajectory {trajectory.record_id!r} has non-finite final reward")
    expected_total = sum(float(value) for value in trajectory.step_rewards) + float(
        trajectory.final_reward
    )
    if not math.isclose(float(trajectory.reward), expected_total, abs_tol=1e-6):
        raise ValueError(
            f"trajectory {trajectory.record_id!r}: reward={trajectory.reward} but "
            f"step/final total={expected_total}"
        )


# ---------------------------------------------------------------------------
# Legacy placeholder
# ---------------------------------------------------------------------------


def _run_vagen_rollout(
    config_path: Path, checkpoint_dir: Path, output_dir: Path,
    num_episodes: int, max_steps: int,
) -> None:
    raise NotImplementedError(
        "Use EnvRolloutCollector with --env-url instead of VAGEN subprocess."
    )


# ---------------------------------------------------------------------------
# JSONL-backed collector (reads pre-collected trajectories from disk)
# ---------------------------------------------------------------------------


class JSONLRolloutCollector:
    """Read trajectories from pre-existing JSONL files/directories.

    用于外部 rollout（如 Slurm 上的 rollout_env.py）生成 JSONL 后，RL trainer
    从 JSONL 消费轨迹的离线场景。

    支持：
    - 指定一个或多个 JSONL 文件或目录（目录下递归搜索 ``*.jsonl`` 和 ``*.jsonl.gz``）
    - 按 iteration 循环读取（数据轮转，不会终止训练）
    - 分布式环境下所有 rank 调用 ``collect()`` 得到相同结果（确定性轮转）

    数据轮转策略：
    - 首次调用 ``collect()`` 时加载所有 JSONL 文件中的所有轨迹并 shuffle
    - 每次调用返回 ``num_episodes`` 条，内部指针前进
    - 指针到达末尾时自动回到开头（loop=True）
    - 所有 rank 同时调用、相同调用次数 → 得到相同轨迹序列
    """

    def __init__(self, sources: list[Path] | None = None, loop: bool = True) -> None:
        self._sources: list[Path] = list(sources) if sources else []
        self._loop = loop
        self._all_trajectories: list[RolloutTrajectory] | None = None
        self._cursor: int = 0
        self._call_count: int = 0  # 外部 collect 调用次数（用于分布式调试）

    def _load_all(self) -> list[RolloutTrajectory]:
        """首次调用时加载所有 JSONL 源文件中的轨迹并 shuffle。"""
        all_trajs: list[RolloutTrajectory] = []
        files = self._expand_sources()
        if not files:
            raise FileNotFoundError(
                f"JSONLRolloutCollector: 未找到任何 JSONL 文件，sources={self._sources}"
            )
        for fpath in files:
            try:
                loaded = load_trajectories(fpath)
                all_trajs.extend(loaded)
            except Exception as e:
                print(json.dumps({"jsonl_load_warning": str(fpath), "error": str(e)}),
                      flush=True)
        if not all_trajs:
            raise ValueError(
                f"JSONLRolloutCollector: 从 {len(files)} 个 JSONL 文件中未读到任何有效轨迹"
            )
        # shuffle 一次保证数据不按原始顺序；分布式下所有 rank 读同一 shuffle 结果
        import random
        rng = random.Random(42)
        rng.shuffle(all_trajs)
        return all_trajs

    def _expand_sources(self) -> list[Path]:
        """展开 sources 中的目录 → 所有 .jsonl / .jsonl.gz 文件。"""
        files: list[Path] = []
        for src in self._sources:
            if src.is_dir():
                for pat in ("**/*.jsonl", "**/*.jsonl.gz"):
                    files.extend(sorted(src.glob(pat)))
            elif src.exists():
                files.append(src)
        return files

    @property
    def total_trajectories(self) -> int:
        if self._all_trajectories is None:
            self._all_trajectories = self._load_all()
        return len(self._all_trajectories)

    def collect(
        self,
        *,
        num_episodes: int,
        max_steps_per_episode: int = 20,
        output_dir: Path | None = None,
    ) -> list[RolloutTrajectory]:
        """返回 ``num_episodes`` 条轨迹，从已加载的源数据中轮转读取。

        所有 rank 调用时都会拿到相同的轨迹序列（确定性），保证 FSDP 训练一致性。
        """
        self._call_count += 1
        if self._all_trajectories is None:
            self._all_trajectories = self._load_all()

        total = len(self._all_trajectories)
        if total == 0:
            return []

        result: list[RolloutTrajectory] = []
        needed = num_episodes
        while needed > 0:
            remaining = total - self._cursor
            take = min(needed, remaining)
            if take > 0:
                result.extend(self._all_trajectories[self._cursor:self._cursor + take])
                self._cursor += take
                needed -= take
            if self._cursor >= total:
                if self._loop:
                    self._cursor = 0
                else:
                    break  # 不循环，剩余不足
        return result


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def save_trajectories(trajectories: list[RolloutTrajectory], output_dir: Path) -> Path:
    """Write trajectories to a Nimloth JSONL file, one record per line."""
    output_dir.mkdir(parents=True, exist_ok=True)
    jsonl_path = output_dir / "trajectories.jsonl"
    with jsonl_path.open("w", encoding="utf-8") as f:
        for traj in trajectories:
            f.write(json.dumps(traj.to_record(), ensure_ascii=False) + "\n")
    return jsonl_path


def load_trajectories(jsonl_path: Path) -> list[RolloutTrajectory]:
    """Read trajectories from a Nimloth JSONL or JSONL.GZ file."""
    trajectories: list[RolloutTrajectory] = []
    opener = gzip.open if jsonl_path.suffix == ".gz" else Path.open
    with opener(jsonl_path, "rt", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            trajectory = RolloutTrajectory.from_record(json.loads(line))
            validate_rollout_trajectory(trajectory)
            trajectories.append(trajectory)
    return trajectories
